### ISSUE TITLE
Cannot download a theme

### ISSUE THREAD

**Issue by martintidman** [jquery/themeroller.jquerymobile.com#221] opened 2015-09-10 13:21 UTC
Hi,

First of all, thanks for a great tool!

Unfortunately I'm having trouble downloading a theme from it today.  I've made the changes I need to but when I click on download, set a theme name and then click to download, a broken version of the page is loaded. It looks like the base URL is being changed and page is reloading but a zip file isn't being downloaded.

I've tried it under the latest Chrome and IE 11 under Windows 8.1 and Safari and Chrome under OSX 10.9.5 (Mavericks) all with the same result.

Many Thanks

Martin

**Comment by agcolom** [comment] 2015-09-10 13:29
@martintidman Thank you very much for reporting. 
This is a duplicate of https://github.com/jquery/jquery-mobile/issues/8284 (where you will find some more details of the problem).
@arschmitz @jaspermdegroot We probably should only keep one of these open. Should we close https://github.com/jquery/jquery-mobile/issues/8284 as this issue here seems to be in the most appropriate repo?

**Comment by arschmitz** [comment] 2015-09-10 20:48
This should be fixed now

**Comment by gnarf** [comment] 2015-09-11 00:51
What was the problem? I looked briefly but didn't detect any issues

**Comment by arschmitz** [comment] 2015-09-11 00:53
@gnarf there were file systems issues and the filesystem was read only. Adam rebooted and everything was good.

**Closed by arschmitz** 2015-09-11 00:53 UTC

**Comment by gnarf** [comment] 2015-09-11 00:56
Huh... Maybe I checked it after that was solved, I feel like I would have
noticed a read only fs

**Comment by martintidman** [comment] 2015-09-11 06:48
Thanks to all for sorting this out.
