### ISSUE TITLE
Cannot download a theme from jquery theme roller 1.4.5 version

### ISSUE THREAD

**Issue by HDShruthi** [jquery/themeroller.jquerymobile.com#232] opened 2016-08-22 10:28 UTC
I am not able to download the theme roller zip file. It shows some static html page. Please guide.

**Comment by jaspermdegroot** [comment] 2016-08-22 11:38
Closing as duplicate of https://github.com/jquery/themeroller.jquerymobile.com/issues/230

**Closed by jaspermdegroot** 2016-08-22 11:38 UTC
