### ISSUE TITLE
Not working today using Firefox/Chrome

### ISSUE THREAD

**Issue by FlossyWeb** [jquery/themeroller.jquerymobile.com#220] opened 2015-06-01 14:19 UTC
Hi there,

First thank you for your magnificent work.
Today I'm trying to make a new custom theme using the themeroller and it appears that it doesn't work when I browse it using Firefox/Chrome (up to date browsers), still works using ie though !
The site shows all popup contents on top and the themeroller itself is broken and displayed at the bottom.

Kind regards, François.

**Comment by arschmitz** [comment] 2015-06-01 14:23
@FlossyWeb Hi thank you for reporting this. I just tried it on both latest Chrome and latest Firefox on OSX 10.10 and everything seemed to be working fine as far as i can see.

Can you see if there are any errors and maybe get a screen shot of what is happening?

**Comment by jaspermdegroot** [comment] 2015-06-01 14:29
I can't reproduce it either. I tested on both OS X and Windows.
@FlossyWeb does it still happen after you cleaned your cache or in an incognito window (cache disabled)?

**Comment by FlossyWeb** [comment] 2015-06-01 14:37
Hi guys,

here attached are the screenshots and firebug reports this error :
Error: Permission denied to access property "document"
https://themeroller.jquerymobile.com/js/lib/jquery.js
Line 3

I've figured out what the issue is, it is related to the use of Avira's web
protection plug-in, when I deactivate this addon the site works perfectly.
Avira's plug-in inserts an iframe into every visited page, it seems to
bother the themeroller.

Kind regards, François.

François-Régis SIMON - www.flossyweb.com - 0622403051 -
contact@flossyweb.com


2015-06-01 16:29 GMT+02:00 Jasper de Groot <notifications@github.com>:

**Comment by FlossyWeb** [comment] 2015-06-01 14:39
![screen1_top](https://cloud.githubusercontent.com/assets/2885706/7915283/cd66bcc6-087c-11e5-837c-1c69f944b2f5.png)
![screen2_mid](https://cloud.githubusercontent.com/assets/2885706/7915284/cd70ee4e-087c-11e5-8587-44933191cbd2.png)
![screen3_bot](https://cloud.githubusercontent.com/assets/2885706/7915285/cd775806-087c-11e5-88e1-50c9b4e90f53.png)

**Comment by arschmitz** [comment] 2015-06-01 14:41
@FlossyWeb Thank you since this is not actually a problem with the thememroller and is a problem with your browser plugin I'm going to close this as not a bug.

**Closed by arschmitz** 2015-06-01 14:41 UTC
