### ISSUE TITLE
Cannot download a theme

### ISSUE THREAD

**Issue by johannesdorsey** [jquery/themeroller.jquerymobile.com#231] opened 2016-08-18 09:03 UTC
The zip file isn't downloading.

**Comment by agcolom** [comment] 2016-08-18 09:20
@johannesdorsey Thanks for letting us know. This is a duplicate of #230 so I am closing this one to only keep one issue open and we'll take a look at what's causing this issue.

**Closed by agcolom** 2016-08-18 09:20 UTC
