### ISSUE TITLE
Themeroller input boxes don't refresh after import

### ISSUE THREAD

**Issue by sogen** [jquery/themeroller.jquerymobile.com#213] opened 2014-12-08 18:13 UTC
How to reproduce:
1.- Make 3 or 4 themes ("Add swatch.." 3 or 4 times)
2.- Make some customization
3.- Export zip
4.- Import unzipped CSS back to Themereoller (press Import, then press Cancel)
5.- **RESULT**: Input boxes don't reflect new values.
**EXPECTED** RESULT: Input boxes show imported values.

OS: Win 7 64bit
Happes in all Browsers: **Chrome** 39.0.2171.71 m, **Firefox** 34.0, **IE** 11.0.9600.etc

![bug](https://cloud.githubusercontent.com/assets/2784323/5344267/21faa4be-7ecb-11e4-821d-c900c486eb86.png)

**Comment by arschmitz** [comment] 2015-01-09 19:33
@sogen If your pressing cancel your not actually importing your theme. Closing this as a duplicate of https://github.com/jquery/themeroller.jquerymobile.com/issues/214

**Closed by arschmitz** 2015-01-09 19:33 UTC
