### ISSUE TITLE
Cannot download the theme

### ISSUE THREAD

**Issue by Netpolice** [jquery/themeroller.jquerymobile.com#230] opened 2016-08-18 08:24 UTC
Cannot download the theme.

**Comment by Netpolice** [comment] 2016-08-18 08:50
After click the "Download Zip", it is not downloading the ZIP file.

**Comment by agcolom** [comment] 2016-08-18 09:37
I can confirm the issue.

**Comment by grahamphilpot** [comment] 2016-08-18 16:23
I'm getting the same issue. Can create theme but can't download it.

**Comment by tolesolo** [comment] 2016-08-19 00:48
same with me, up

**Comment by Netpolice** [comment] 2016-08-20 02:34
When it can be fixed? Urgent.

**Comment by jaspermdegroot** [comment] 2016-08-20 07:12
@arschmitz - I remember that we had this problem before and that time the cause was lack of space on the server so it was fixed by deleting old ZIPs. Do you have access to the server so you can check this?

To everyone who is running into this issue: we are aware of it and working on it. No need to comment that you have the same problem and/or how urgent it is. Thanks!

**Comment by jaspermdegroot** [comment] 2016-08-22 11:37
@arschmitz - See also https://github.com/jquery/themeroller.jquerymobile.com/issues/221

**Comment by Michael-F-Ellis** [comment] 2016-08-22 21:32
Is there an estimate of when the site will be working again? Thanks!

**Comment by nnamdy2** [comment] 2016-08-23 07:20
Just to announce that it's working now. Tried it today and it works fine.

**Comment by jaspermdegroot** [comment] 2016-08-23 07:55
@nnamdy2 - Thanks for the update.

I am closing this issue as fixed. If anyone still runs into problems, please comment here and we will reopen.

**Closed by jaspermdegroot** 2016-08-23 07:55 UTC

**Comment by arschmitz** [comment] 2016-08-23 11:59
@jaspermdegroot yes this is fixed @aulvi and i cleaned out server last night you were right about disk space thank you!

**Comment by moilejter** [comment] 2019-10-24 04:22
This is happening to me now... Same issue?
